
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - "*ci*"

name: Check and Lint for symex backend

defaults:
  run:
    working-directory: symex

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - name: cargo_clippy
        run: |
          rustup target list
          cargo +nightly clippy 
          cargo +nightly clippy --examples
  doc:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - name: doc doc
        run: |
          rustup target list
          cargo +nightly doc
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: cargo_check
        run: |
          cargo +nightly check
          cargo +nightly check --examples

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - name: fmt check
        run: |
          cargo +nightly fmt --all -- --check

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: cargo build
        run: |
          ls -la
          cargo +nightly build --release
          cargo +nightly build --examples --release

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: cargo test
        run: |
          ls -la
          # HACK: Install bitwuzla dependencies on the fly, this needs to be cached.
          sudo apt-get update
          sudo apt-get install -y libgmp-dev libmpfr-dev ninja-build meson cython3 python3-pytest libgtest-dev libcadical-dev
          cargo test --features=build-bitwuzla,exact
